# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

submodules:
  include: []
  recursive: false

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - build-essential
  commands:
    - pip install -r docs/requirements.txt
    - make build_doc -f build.mk
    - cp -r docs/build _readthedocs/html

# Build documentation in the docs/ directory with Sphinx
#sphinx:
#  builder: html
#  configuration: docs/conf.py

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: docs/requirements.txt